
export const FETCH_CONFIG = "FETCH_CONFIG";
export const FETCH_CONFIG_SUCCESS = "FETCH_CONFIG_SUCCESS";
export const FETCH_CONFIG_FAILED = "FETCH_CONFIG_FAILED";
export const FETCH_CONTENT = "FETCH_CONTENT";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_FAILED = "FETCH_CONTENT_FAILED";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";``
export const FETCH_REPO_LIST = "FETCH_REPO_LIST";
export const FETCH_REPO_LIST_SUCCESS = "FETCH_REPO_LIST_SUCCESS";
export const FETCH_REPO_LIST_FAILED = "FETCH_REPO_LIST_FAILED";
//redirect
export const REDIRECT_SAMPLE2 = "REDIRECT_SAMPLE2";